//! macOS rollback is scoped to this exact App bundle, never a caller path.
use std::{
    fs,
    path::{Path, PathBuf},
    process::{Command, Stdio},
};
use tauri::{AppHandle, Manager};

pub(crate) fn app_bundle() -> Result<PathBuf, String> {
    app_bundle_at(&std::env::current_exe().map_err(|_| "app_bundle_required")?)
}

// The pinned macOS updater moves the old App bundle away before moving the new
// one in, so callers that must verify the installed App is still in place
// (failed replacement recovery) resolve it from the running executable.
// Path-level so synthetic App layouts are testable without a signed build.
//
// This is a layout-and-runnability check, not a signature check: the bundle
// must keep its Info.plist AND its executable. A partially removed bundle —
// executable deleted while Info.plist (and the runtime identity) survives a
// failed replacement — must not verify, or the safe-restart predicate would
// discard the recovery journal over an unbootable App. Signature integrity
// stays at the `copy` boundary's `codesign --verify` check.
pub(crate) fn app_bundle_at(executable: &Path) -> Result<PathBuf, String> {
    let bundle = executable
        .parent()
        .and_then(Path::parent)
        .and_then(Path::parent)
        .ok_or("app_bundle_required")?;
    if bundle.extension().and_then(|s| s.to_str()) != Some("app")
        || !bundle.join("Contents/Info.plist").is_file()
        || !bundle_executable_is_present(executable, bundle)
    {
        return Err("app_bundle_required".into());
    }
    Ok(bundle.to_path_buf())
}

// The running binary keeps executing after the updater deletes it, so a
// missing file at the executable's own path is exactly the "old bundle was
// moved away / partially removed" state layout verification must reject.
// When Info.plist declares CFBundleExecutable, that declared binary must
// exist too: the bundle launches what Info.plist names, not any surviving
// neighbor. An unreadable (e.g. binary) plist skips the declared-name check
// without weakening the executable-presence check above.
fn bundle_executable_is_present(executable: &Path, bundle: &Path) -> bool {
    if !executable.is_file() {
        return false;
    }
    match declared_bundle_executable(bundle) {
        Some(declared) => {
            !declared.is_empty()
                && bundle.join("Contents/MacOS").join(declared).is_file()
        }
        None => true,
    }
}

fn declared_bundle_executable(bundle: &Path) -> Option<String> {
    let plist = fs::read_to_string(bundle.join("Contents/Info.plist")).ok()?;
    let key = "<key>CFBundleExecutable</key>";
    let rest = &plist[plist.find(key)? + key.len()..];
    let open = rest.find("<string>")? + "<string>".len();
    let value = &rest[open..];
    let close = value.find("</string>")?;
    Some(value[..close].trim().to_string())
}

fn root(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(app
        .path()
        .app_local_data_dir()
        .map_err(|_| "backup_unavailable")?
        .join("update-backup"))
}
fn copy(source: &Path, destination: &Path) -> Result<(), String> {
    let status = Command::new("ditto")
        .arg(source)
        .arg(destination)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map_err(|_| "backup_failed")?;
    if !status.success() {
        return Err("backup_failed".into());
    }
    let verified = Command::new("codesign")
        .args(["--verify", "--deep", "--strict"])
        .arg(destination)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map_err(|_| "backup_failed")?;
    if !verified.success() {
        return Err("backup_failed".into());
    }
    Ok(())
}

pub fn available(app: &AppHandle) -> bool {
    cfg!(target_os = "macos")
        && root(app).is_ok_and(|r| r.join("previous/LoopX.app/Contents/Info.plist").is_file())
}

pub fn prepare(app: &AppHandle) -> Result<(), String> {
    if !cfg!(target_os = "macos") {
        return Ok(());
    }
    let bundle = app_bundle()?;
    let root = root(app)?;
    fs::create_dir_all(&root).map_err(|_| "backup_failed")?;
    let temporary = tempfile::tempdir_in(&root).map_err(|_| "backup_failed")?;
    copy(&bundle, &temporary.path().join("LoopX.app"))?;
    fs::write(
        temporary.path().join("version"),
        app.package_info().version.to_string(),
    )
    .map_err(|_| "backup_failed")?;
    let previous = root.join("previous");
    // Retain the old backup until the new verified backup is durable. This
    // directory contains only backups generated by this updater.
    if previous.exists() {
        let older = root.join(format!(
            "older-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_millis()
        ));
        fs::rename(&previous, older).map_err(|_| "backup_failed")?;
    }
    fs::rename(temporary.path(), previous).map_err(|_| "backup_failed")?;
    Ok(())
}

pub fn restore(app: &AppHandle) -> Result<(), String> {
    if !available(app) {
        return Err("backup_unavailable".into());
    }
    let bundle = app_bundle()?;
    let staging = tempfile::tempdir_in(bundle.parent().ok_or("app_bundle_required")?)
        .map_err(|_| "rollback_failed")?;
    let candidate = staging.path().join("LoopX.app");
    copy(&root(app)?.join("previous/LoopX.app"), &candidate)?;
    let failed = staging.path().join("failed.app");
    let version = fs::read_to_string(root(app)?.join("previous/version"))
        .map_err(|_| "backup_unavailable")?;
    // Once an installed App can move here, never let TempDir cleanup erase it
    // on a failed second rename (including a failed restoration rename).
    let _preserved = staging.keep();
    crate::bundled_runtime::record_pending(app, version.trim(), "rollback")?;
    replace_bundle(&bundle, &candidate, &failed)?;
    // Keep the failed App recoverable too. Never delete a user's installed App.
    Ok(())
}

fn replace_bundle(bundle: &Path, candidate: &Path, failed: &Path) -> Result<(), String> {
    fs::rename(bundle, failed).map_err(|_| "rollback_failed")?;
    if fs::rename(candidate, bundle).is_err() {
        let _ = fs::rename(failed, bundle);
        return Err("rollback_failed".into());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn failed_replacement_restores_original() {
        let dir = tempfile::tempdir().unwrap();
        let app = dir.path().join("installed.app");
        fs::create_dir(&app).unwrap();
        fs::write(app.join("original"), "keep").unwrap();
        assert!(replace_bundle(
            &app,
            &dir.path().join("missing.app"),
            &dir.path().join("failed.app")
        )
        .is_err());
        assert_eq!(fs::read_to_string(app.join("original")).unwrap(), "keep");
    }

    #[test]
    fn synthetic_app_layout_verifies_only_when_the_bundle_survives() {
        // A synthetic App layout stands in for the second-rename failure of
        // the pinned macOS installer: when the original location is emptied,
        // the running executable's ancestor bundle must stop verifying, which
        // is what blocks the safe-restart promise after a failed replacement.
        let dir = tempfile::tempdir().unwrap();
        let app = dir.path().join("Synthetic.app/Contents/MacOS");
        fs::create_dir_all(&app).unwrap();
        let executable = app.join("loopx-control-plane");
        fs::write(&executable, "binary").unwrap();
        fs::write(app.join("../Info.plist"), "plist").unwrap();
        assert_eq!(
            app_bundle_at(&executable),
            Ok(dir.path().join("Synthetic.app"))
        );
        // The updater's first rename moved the original away: no bundle with
        // an Info.plist remains at the executable's ancestors.
        fs::remove_file(app.join("../Info.plist")).unwrap();
        assert_eq!(
            app_bundle_at(&executable),
            Err("app_bundle_required".into())
        );
        // A bare executable outside any .app bundle never verifies.
        let loose = dir.path().join("bin/loopx-control-plane");
        fs::create_dir_all(loose.parent().unwrap()).unwrap();
        fs::write(&loose, "binary").unwrap();
        assert_eq!(app_bundle_at(&loose), Err("app_bundle_required".into()));
    }

    #[test]
    fn executable_removal_while_info_plist_remains_stops_verifying() {
        // Review round 3 counterexample: the pinned macOS updater's failed
        // replacement can leave a partially removed bundle — Info.plist and
        // the runtime identity survive while the executable is gone (a
        // running process keeps executing its deleted binary, so the path
        // simply stops existing). Layout verification must fail here so the
        // safe-restart predicate cannot discard the journal and promise a
        // safe restart over an unbootable App.
        let dir = tempfile::tempdir().unwrap();
        let contents = dir.path().join("Partial.app/Contents");
        fs::create_dir_all(contents.join("MacOS")).unwrap();
        fs::write(contents.join("Info.plist"), "plist").unwrap();
        let executable = contents.join("MacOS/loopx-control-plane");
        fs::write(&executable, "binary").unwrap();
        assert!(app_bundle_at(&executable).is_ok());
        fs::remove_file(&executable).unwrap();
        assert_eq!(
            app_bundle_at(&executable),
            Err("app_bundle_required".into())
        );
    }

    #[test]
    fn declared_bundle_executable_must_be_present_when_plist_names_it() {
        // When Info.plist declares CFBundleExecutable, that exact binary
        // must exist in Contents/MacOS: a bundle whose declared executable
        // was removed — even with another file left behind — cannot run the
        // binary the bundle claims to launch.
        let dir = tempfile::tempdir().unwrap();
        let contents = dir.path().join("Declared.app/Contents");
        fs::create_dir_all(contents.join("MacOS")).unwrap();
        fs::write(
            contents.join("Info.plist"),
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\
             <plist version=\"1.0\"><dict>\
             <key>CFBundleExecutable</key><string>loopx-control-plane</string>\
             </dict></plist>",
        )
        .unwrap();
        let survivor = contents.join("MacOS/unrelated-helper");
        fs::write(&survivor, "binary").unwrap();
        assert_eq!(
            app_bundle_at(&survivor),
            Err("app_bundle_required".into())
        );
        // With the declared executable restored beside the survivor the
        // bundle is a runnable layout again.
        let declared = contents.join("MacOS/loopx-control-plane");
        fs::write(&declared, "binary").unwrap();
        assert!(app_bundle_at(&survivor).is_ok());
        assert!(app_bundle_at(&declared).is_ok());
    }

    #[test]
    #[ignore = "requires LOOPX_TEST_APP from a signed macOS build"]
    fn real_backup_copy_retains_signature() {
        let source = std::env::var("LOOPX_TEST_APP").unwrap();
        let dir = tempfile::tempdir().unwrap();
        let copied = dir.path().join("LoopX.app");
        copy(Path::new(&source), &copied).unwrap();
        assert!(copied
            .join("Contents/Resources/runtime/identity.json")
            .is_file());
    }
}
